application: cenanafte
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /adminpanel
  script: admin.application
  login: admin
- url: /assets
  static_dir: templates/assets
- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest

admin_console:
  pages:
  - name: Urejanje podatkov
    url: /adminpanel